# This is a basic workflow to help you get started with Actions

name: pullrequestreviewnotify

# Controls when the workflow will run
on:
  pull_request_review:
    types: [submitted, edited, dismissed]

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy Stage
      uses: CamiloGarciaLaRotta/watermelon-http-client@v1
      with:
         url: 'https://t2tavamigrations.webhook.office.com/webhookb2/5c7b77bf-ba44-49d8-9293-74ff75bfbe03@2cd74de4-31b3-44ae-b6bb-3b1ffbd9b1d1/IncomingWebhook/24490c6597f04fa9b63e499f05e52cd0/c19dc52d-df6d-40ba-ae70-36ded154271b'
         method: post
         data: '{"Text": "${{ github.event.repository.full_name }}/pulls/${{ github.event.pull_request.number }}"}' 
